general:
  bootstrap_end_time: 300
  stop_time: 3600
  progress: true
  template_directory: shadow.data.template
network:
  use_shortest_path: false
  graph:
    type: gml
    file:
      path: /home/joerg_diesel_rules/tornettools/tornet-0.0001/conf/atlas_v201801.shadow_v2.gml.xz
      compression: xz
hosts:
  4uthority1:
    network_node_id: 1151
    ip_addr: 100.0.0.1
    bandwidth_down: 1000000 kilobit
    bandwidth_up: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address 4uthority1 --Nickname 4uthority1 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 1
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 2
      expected_final_state: running
  4uthority2:
    network_node_id: 1410
    ip_addr: 100.0.0.2
    bandwidth_down: 1000000 kilobit
    bandwidth_up: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address 4uthority2 --Nickname 4uthority2 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 1
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 2
      expected_final_state: running
  4uthority3:
    network_node_id: 1151
    ip_addr: 100.0.0.3
    bandwidth_down: 1000000 kilobit
    bandwidth_up: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address 4uthority3 --Nickname 4uthority3 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 1
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 2
      expected_final_state: running
  relay1exitguard:
    network_node_id: 1854
    ip_addr: 192.42.116.25
    bandwidth_down: 111680 kilobit
    bandwidth_up: 111680 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay1exitguard --Nickname relay1exitguard --defaults-torrc
        torrc-defaults -f torrc
      start_time: 2
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 3
      expected_final_state: running
  relay2exit:
    network_node_id: 277
    ip_addr: 23.129.64.146
    bandwidth_down: 164416 kilobit
    bandwidth_up: 164416 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay2exit --Nickname relay2exit --defaults-torrc torrc-defaults
        -f torrc
      start_time: 3
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 4
      expected_final_state: running
  relay3guard:
    network_node_id: 2029
    ip_addr: 81.169.173.113
    bandwidth_down: 106808 kilobit
    bandwidth_up: 106808 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay3guard --Nickname relay3guard --defaults-torrc torrc-defaults
        -f torrc
      start_time: 4
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 5
      expected_final_state: running
  relay4middle:
    network_node_id: 1035
    ip_addr: 139.162.117.43
    bandwidth_down: 20080 kilobit
    bandwidth_up: 20080 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay4middle --Nickname relay4middle --defaults-torrc torrc-defaults
        -f torrc
      start_time: 5
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 6
      expected_final_state: running
  server1exit:
    network_node_id: 334
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen-server.tgenrc.graphml
      start_time: 300
      expected_final_state: running
  server2exit:
    network_node_id: 24
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen-server.tgenrc.graphml
      start_time: 300
      expected_final_state: running
  server3exit:
    network_node_id: 1645
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen-server.tgenrc.graphml
      start_time: 300
      expected_final_state: running
  server4exit:
    network_node_id: 993
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen-server.tgenrc.graphml
      start_time: 300
      expected_final_state: running
  server5exit:
    network_node_id: 269
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen-server.tgenrc.graphml
      start_time: 300
      expected_final_state: running
  server6exit:
    network_node_id: 1877
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen-server.tgenrc.graphml
      start_time: 300
      expected_final_state: running
  server7exit:
    network_node_id: 604
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen-server.tgenrc.graphml
      start_time: 300
      expected_final_state: running
  server8exit:
    network_node_id: 934
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen-server.tgenrc.graphml
      start_time: 300
      expected_final_state: running
  markovclient1exit:
    network_node_id: 856
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --defaults-torrc torrc-defaults -f torrc
      environment:
        OPENBLAS_NUM_THREADS: '1'
      start_time: 240
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
      expected_final_state: running
    - path: ~/.local/bin/tgen
      args: tgenrc.graphml
      start_time: 300
      expected_final_state: {exited: 0}
  markovclient2exit:
    network_node_id: 623
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --defaults-torrc torrc-defaults -f torrc
      environment:
        OPENBLAS_NUM_THREADS: '1'
      start_time: 240
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
      expected_final_state: running
    - path: ~/.local/bin/tgen
      args: tgenrc.graphml
      start_time: 300
      expected_final_state: {exited: 0}
  markovclient3exit:
    network_node_id: 468
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --defaults-torrc torrc-defaults -f torrc
      environment:
        OPENBLAS_NUM_THREADS: '1'
      start_time: 240
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
      expected_final_state: running
    - path: ~/.local/bin/tgen
      args: tgenrc.graphml
      start_time: 300
      expected_final_state: {exited: 0}
  markovclient4exit:
    network_node_id: 913
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --defaults-torrc torrc-defaults -f torrc
      environment:
        OPENBLAS_NUM_THREADS: '1'
      start_time: 240
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
      expected_final_state: running
    - path: ~/.local/bin/tgen
      args: tgenrc.graphml
      start_time: 300
      expected_final_state: {exited: 0}
  markovclient5exit:
    network_node_id: 1454
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --defaults-torrc torrc-defaults -f torrc
      environment:
        OPENBLAS_NUM_THREADS: '1'
      start_time: 240
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
      expected_final_state: running
    - path: ~/.local/bin/tgen
      args: tgenrc.graphml
      start_time: 300
      expected_final_state: {exited: 0}
  markovclient6exit:
    network_node_id: 1106
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --defaults-torrc torrc-defaults -f torrc
      environment:
        OPENBLAS_NUM_THREADS: '1'
      start_time: 240
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
      expected_final_state: running
    - path: ~/.local/bin/tgen
      args: tgenrc.graphml
      start_time: 300
      expected_final_state: {exited: 0}
  markovclient7exit:
    network_node_id: 1360
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --defaults-torrc torrc-defaults -f torrc
      environment:
        OPENBLAS_NUM_THREADS: '1'
      start_time: 240
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
      expected_final_state: running
    - path: ~/.local/bin/tgen
      args: tgenrc.graphml
      start_time: 300
      expected_final_state: {exited: 0}
  markovclient8exit:
    network_node_id: 1485
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --defaults-torrc torrc-defaults -f torrc
      environment:
        OPENBLAS_NUM_THREADS: '1'
      start_time: 240
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
      expected_final_state: running
    - path: ~/.local/bin/tgen
      args: tgenrc.graphml
      start_time: 300
      expected_final_state: {exited: 0}