general:
  bootstrap_end_time: 300
  stop_time: 3600
  progress: true
  template_directory: shadow.data.template
network:
  use_shortest_path: false
  graph:
    type: gml
    file:
      path: /home/admin/tornettools/tornet-tgentest/conf/atlas_v201801.shadow_v2.gml.xz
      compression: xz
hosts:
  4uthority1:
    network_node_id: 1640
    ip_addr: 100.0.0.1
    bandwidth_down: 1000000 kilobit
    bandwidth_up: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address 4uthority1 --Nickname 4uthority1 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 1
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 2
      expected_final_state: running
  4uthority2:
    network_node_id: 1640
    ip_addr: 100.0.0.2
    bandwidth_down: 1000000 kilobit
    bandwidth_up: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address 4uthority2 --Nickname 4uthority2 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 1
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 2
      expected_final_state: running
  4uthority3:
    network_node_id: 49
    ip_addr: 100.0.0.3
    bandwidth_down: 1000000 kilobit
    bandwidth_up: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address 4uthority3 --Nickname 4uthority3 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 1
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 2
      expected_final_state: running
  relay1exitguard:
    network_node_id: 503
    ip_addr: 104.244.73.190
    bandwidth_down: 130040 kilobit
    bandwidth_up: 130040 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay1exitguard --Nickname relay1exitguard --defaults-torrc
        torrc-defaults -f torrc
      start_time: 2
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 3
      expected_final_state: running
  relay2exit:
    network_node_id: 719
    ip_addr: 108.165.249.5
    bandwidth_down: 156360 kilobit
    bandwidth_up: 156360 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay2exit --Nickname relay2exit --defaults-torrc torrc-defaults
        -f torrc
      start_time: 3
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 4
      expected_final_state: running
  relay3guard:
    network_node_id: 581
    ip_addr: 142.44.243.133
    bandwidth_down: 96048 kilobit
    bandwidth_up: 96048 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay3guard --Nickname relay3guard --defaults-torrc torrc-defaults
        -f torrc
      start_time: 4
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 5
      expected_final_state: running
  relay4middle:
    network_node_id: 978
    ip_addr: 149.154.152.121
    bandwidth_down: 64248 kilobit
    bandwidth_up: 64248 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay4middle --Nickname relay4middle --defaults-torrc torrc-defaults
        -f torrc
      start_time: 5
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 6
      expected_final_state: running
  server1exit:
    network_node_id: 2389
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen-server.tgenrc.graphml
      start_time: 300
      expected_final_state: running
  markovclient1exit:
    network_node_id: 335
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --defaults-torrc torrc-defaults -f torrc
      environment:
        OPENBLAS_NUM_THREADS: '1'
      start_time: 240
      expected_final_state: running
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
      expected_final_state: running
    - path: ~/.local/bin/tgen
      args: tgenrc.graphml
      start_time: 300
      expected_final_state: running